"""fixes created time

Revision ID: 326a9245594b
Revises: 5cee9a79573d
Create Date: 2023-09-08 09:37:30.744781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '326a9245594b'
down_revision = '5cee9a79573d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('created_at',
                              existing_type=sa.VARCHAR(),
                              type_=sa.DateTime(),
                              server_default=sa.text('(CURRENT_TIMESTAMP)'),
                              existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('created_at',
                              existing_type=sa.DateTime(),
                              type_=sa.VARCHAR(),
                              existing_nullable=True)

    # ### end Alembic commands ###
